"""users/investors & startups migration

Revision ID: 773bda61d81a
Revises:
Create Date: 2025-05-03 19:24:11.896435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '773bda61d81a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('STARTUP', 'SUPPORTER', 'INVESTOR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('startup',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('industry', sa.Enum('TECHNOLOGY', 'HEALTHCARE', 'FINANCE', 'EDUCATION', 'RETAIL', 'MANUFACTURING', 'OTHER', name='industry'), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('funding_stage', sa.Enum('IDEA', 'MVP', 'EARLY_STAGE', 'PRESEED', 'SEED', 'SERIES_A', 'SERIES_B', 'SERIES_C', 'IPO', 'MERGER_ACQUISITION', 'OTHER', name='fundingstage'), nullable=False),
    sa.Column('funding_goal', sa.Float(), nullable=True),
    sa.Column('founded_year', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pitch_deck_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('business_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_market', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('competitors', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('founder_id', sa.Uuid(), nullable=False),
    sa.Column('team_members', sa.JSON(), nullable=True),
    sa.Column('funding', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('social_media', sa.JSON(), nullable=True),
    sa.Column('contact', sa.JSON(), nullable=True),
    sa.Column('traction', sa.JSON(), nullable=True),
    sa.Column('use_of_funds', sa.JSON(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['founder_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startup_name'), 'startup', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_startup_name'), table_name='startup')
    op.drop_table('startup')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
