"""Add InvestorProfile, PitchDeck, and PitchMessage models

Revision ID: a48f33b900c7
Revises: 087394feae48
Create Date: 2025-06-05 17:31:04.702875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a48f33b900c7'
down_revision: Union[str, None] = '087394feae48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investorprofile',
    sa.Column('firm_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('twitter_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('investment_focus', sa.JSON(), nullable=True),
    sa.Column('preferred_stages', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_investorprofile_firm_name'), 'investorprofile', ['firm_name'], unique=False)
    op.create_table('pitchdeck',
    sa.Column('file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('founder_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['founder_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pitchmessage',
    sa.Column('message_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'VIEWED', 'RESPONDED', 'ARCHIVED', name='pitchstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('founder_id', sa.Uuid(), nullable=False),
    sa.Column('investor_id', sa.Uuid(), nullable=False),
    sa.Column('pitch_deck_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['founder_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['investor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pitch_deck_id'], ['pitchdeck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pitchmessage')
    op.drop_table('pitchdeck')
    op.drop_index(op.f('ix_investorprofile_firm_name'), table_name='investorprofile')
    op.drop_table('investorprofile')
    # ### end Alembic commands ###
