"""initial migration

Revision ID: d6bfa3df105a
Revises: 
Create Date: 2025-06-30 17:10:50.002601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd6bfa3df105a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investorprofile',
    sa.Column('firm_name', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('twitter_url', sa.String(), nullable=True),
    sa.Column('investment_focus', sa.JSON(), nullable=True),
    sa.Column('preferred_stages', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_investorprofile_firm_name'), 'investorprofile', ['firm_name'], unique=False)
    op.create_table('pitchdeck',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('founder_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['founder_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pitchmessage',
    sa.Column('message_content', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'VIEWED', 'RESPONDED', 'ARCHIVED', name='pitchstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('founder_id', sa.Uuid(), nullable=False),
    sa.Column('investor_id', sa.Uuid(), nullable=False),
    sa.Column('pitch_deck_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['founder_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['investor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pitch_deck_id'], ['pitchdeck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('startup', sa.Column('founded_year', sa.String(), nullable=True))
    op.add_column('startup', sa.Column('team_size', sa.Integer(), nullable=True))
    op.add_column('startup', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('startup', sa.Column('demo_video_url', sa.String(), nullable=True))
    op.add_column('startup', sa.Column('business_model', sa.String(), nullable=True))
    op.add_column('startup', sa.Column('target_market', sa.String(), nullable=True))
    op.add_column('startup', sa.Column('competitors', sa.String(), nullable=True))
    op.add_column('startup', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.add_column('startup', sa.Column('team_members', sa.JSON(), nullable=True))
    op.add_column('startup', sa.Column('funding', sa.JSON(), nullable=True))
    op.add_column('startup', sa.Column('metrics', sa.JSON(), nullable=True))
    op.add_column('startup', sa.Column('social_media', sa.JSON(), nullable=True))
    op.add_column('startup', sa.Column('contact', sa.JSON(), nullable=True))
    op.add_column('startup', sa.Column('traction', sa.JSON(), nullable=True))
    op.add_column('startup', sa.Column('use_of_funds', sa.JSON(), nullable=True))
    op.add_column('startup', sa.Column('timeline', sa.JSON(), nullable=True))
    op.alter_column('startup', 'funding_goal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index(op.f('ix_startup_is_published'), 'startup', ['is_published'], unique=False)
    op.add_column('user', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('reset_token_expires', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('verification_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('verification_token_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verification_token_expires')
    op.drop_column('user', 'verification_token')
    op.drop_column('user', 'reset_token_expires')
    op.drop_column('user', 'reset_token')
    op.drop_index(op.f('ix_startup_is_published'), table_name='startup')
    op.alter_column('startup', 'funding_goal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('startup', 'timeline')
    op.drop_column('startup', 'use_of_funds')
    op.drop_column('startup', 'traction')
    op.drop_column('startup', 'contact')
    op.drop_column('startup', 'social_media')
    op.drop_column('startup', 'metrics')
    op.drop_column('startup', 'funding')
    op.drop_column('startup', 'team_members')
    op.drop_column('startup', 'is_published')
    op.drop_column('startup', 'competitors')
    op.drop_column('startup', 'target_market')
    op.drop_column('startup', 'business_model')
    op.drop_column('startup', 'demo_video_url')
    op.drop_column('startup', 'logo_url')
    op.drop_column('startup', 'team_size')
    op.drop_column('startup', 'founded_year')
    op.drop_table('pitchmessage')
    op.drop_table('pitchdeck')
    op.drop_index(op.f('ix_investorprofile_firm_name'), table_name='investorprofile')
    op.drop_table('investorprofile')
    # ### end Alembic commands ###
