"""add_demo_video_url_to_startup

Revision ID: f02892a2c96a
Revises: 220e24ddac5e
Create Date: 2025-06-25 11:38:17.003831

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f02892a2c96a"
down_revision: Union[str, None] = "220e24ddac5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "startup",
        sa.Column("demo_video_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("startup", "demo_video_url")
    # ### end Alembic commands ###
