# .github/workflows/deploy-cloudrun.yml

name: Deploy to Cloud Run

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment to deploy to
        default: Production - startup-connect-backend

env:
  DOCKERFILE_NAME: "Dockerfile" # Path to your Dockerfile relative to the repo root

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'Production - startup-connect-backend' }}
    permissions:
      contents: "read"
      id-token: "write" # This is crucial for Workload Identity Federation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          service_account: ${{ secrets.SA_EMAIL }}
          workload_identity_provider: ${{ secrets.WIF_PROVIDER_FULL_PATH }}

      - name: Configure Docker to use Artifact Registry
        run: gcloud --quiet auth configure-docker "${{ vars.GCP_AR_REPO_URL }}"

      - name: Build and push Docker image to Artifact Registry
        run: |
          cd backend
          IMAGE_PATH="${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.AR_REPO_NAME }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}"
          echo "Building image: ${IMAGE_PATH}"
          docker build -t "${IMAGE_PATH}" -f "${{ env.DOCKERFILE_NAME }}" .
          echo "Pushing image to Artifact Registry..."
          docker push "${IMAGE_PATH}"
          echo "IMAGE_PATH=${IMAGE_PATH}" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          echo "Deploying Cloud Run service: ${{ vars.CLOUD_RUN_SERVICE_NAME }}"
          gcloud run deploy ${{ vars.CLOUD_RUN_SERVICE_NAME }} \
            --image "${{ env.IMAGE_PATH }}" \
            --region "${{ vars.GCP_REGION }}" \
            --platform "managed" \
            --allow-unauthenticated \
            --min-instances 0 \
            --max-instances 1 \
            --project="${{ vars.GCP_PROJECT_ID }}"
          echo "Cloud Run deployment complete."

      - name: Get Cloud Run service URL
        run: |
          SERVICE_URL=$(gcloud run services describe ${{ vars.CLOUD_RUN_SERVICE_NAME }} \
            --region "${{ vars.GCP_REGION }}" \
            --project="${{ vars.GCP_PROJECT_ID }}" \
            --format="value(status.url)")
          echo "Cloud Run Service URL: ${SERVICE_URL}"
          echo "SERVICE_URL=${SERVICE_URL}" >> $GITHUB_ENV
